# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reimbursement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_bought',
            field=models.FloatField(default=0),
        ),
    ]
