# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0002_auto_20171214_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Space')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='items_storage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='supplies_tracker.Item'),
        ),
        migrations.AddField(
            model_name='items_storage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='supplies_tracker.Storage'),
        ),
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ManyToManyField(related_name='item', through='supplies_tracker.Items_Storage', to='supplies_tracker.Storage'),
        ),
    ]
