# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0003_auto_20171228_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
