# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0004_auto_20171228_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
