# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0005_auto_20171230_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='space_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Space'),
        ),
    ]
