# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0009_auto_20180105_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='user_id',
            new_name='user',
        ),
    ]
