# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0010_auto_20180105_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
