# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0011_auto_20180105_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
