# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0013_auto_20180105_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.User'),
            preserve_default=False,
        ),
    ]
