# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0014_auto_20180105_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='space_id',
            new_name='space',
        ),
    ]
