# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0015_auto_20180105_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='storages',
            field=models.ManyToManyField(related_name='Storage', through='supplies_tracker.Items_Storage', to='supplies_tracker.Storage'),
        ),
        migrations.AddField(
            model_name='storage',
            name='items',
            field=models.ManyToManyField(related_name='Item', through='supplies_tracker.Items_Storage', to='supplies_tracker.Item'),
        ),
        migrations.AlterField(
            model_name='items_storage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Item'),
        ),
        migrations.AlterField(
            model_name='items_storage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Storage'),
        ),
    ]
