# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0016_auto_20180106_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Space'),
        ),
        migrations.AlterUniqueTogether(
            name='items_storage',
            unique_together=set([('storage', 'item')]),
        ),
    ]
