# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0018_auto_20180111_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='items',
            new_name='item',
        ),
    ]
