# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0019_auto_20180111_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items_storage',
            old_name='item',
            new_name='items',
        ),
        migrations.AlterUniqueTogether(
            name='items_storage',
            unique_together=set([('storage', 'items')]),
        ),
    ]
