# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0020_auto_20180111_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
