# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0022_auto_20180114_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reimbursement',
            field=models.FloatField(default=0, null=True),
        ),
    ]
