# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0026_auto_20180117_1114'),
        ('supplies_tracker', '0023_auto_20180116_2022'),
    ]

    operations = [
    ]
