# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0027_merge_20180119_0758'),
        ('supplies_tracker', '0027_merge_20180117_1808'),
    ]

    operations = [
    ]
