# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0028_merge_20180119_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_bought',
            field=models.FloatField(default=0, verbose_name='How much does this cost to buy?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reimbursement',
            field=models.FloatField(default=0, null=True, verbose_name='How much do you make? (Fill if you sell the items, or provide them against donation)'),
        ),
    ]
