# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0030_auto_20180121_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items_storage',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='items_storage',
            unique_together=set([('storage', 'item')]),
        ),
    ]
