# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0031_auto_20180122_2316'),
        ('supplies_tracker', '0031_auto_20180123_0718'),
    ]

    operations = [
    ]
